default_language_version:
  python: python3.8

exclude: "^$"

fail_fast: false

repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py38-plus]

  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.12.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "3.2"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict

  - repo: https://github.com/rtts/djhtml
    rev: v1.5.2
    hooks:
      - id: djhtml
        args:
          - --tabwidth=2

  - repo: https://github.com/thibaudcolas/curlylint
    rev: v0.13.1
    hooks:
      - id: curlylint

  - repo: https://github.com/pycqa/isort
    rev: 5.11.3
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
      - id: black
        exclude: "^.*/migrations/.*.py$"
        args: [--line-length=79, --safe]

  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==22.12.6
          - flake8-comprehensions==3.10.1
          - flake8-no-pep420==2.3.0
          - flake8-tidy-imports==4.8.0

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.0
    hooks:
      - id: python-safety-dependencies-check
        name: safety
        always_run: true
        exclude: ".*"
        verbose: true
        args: ["requirements.txt", "--ignore=51457"]

  - repo: local
    hooks:
      - id: npm-audit
        name: npm-audit
        language: system
        entry: npm audit --audit-level=critical
        always_run: true
        exclude: ".*"
