default_language_version:
  python: python3.8

exclude: "^$"

fail_fast: false

repos:
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.12.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "3.2"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict

  - repo: https://github.com/rtts/djhtml
    rev: v1.5.2
    hooks:
      - id: djhtml
        args:
          - --tabwidth=2

  - repo: https://github.com/thibaudcolas/curlylint
    rev: v0.13.1
    hooks:
      - id: curlylint

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.32.0
    hooks:
      - id: eslint
        args: [--fix]
        additional_dependencies:
          - eslint@7.32.0
          - eslint-config-developit@1.2.0
          - eslint-config-google@0.14.0
          - eslint-config-preact@1.1.4
          - eslint-config-prettier@8.3.0
          - eslint-plugin-prettier@3.4.0
          - "@babel/eslint-parser@7.14.7"
          - "@typescript-eslint/parser"
          - "@typescript-eslint/eslint-plugin"
        exclude: "^.*\\.min\\..*$"
        files: \.[jt]sx?$
        types: [file]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.8.1
        files: \.js$
        exclude: "^.*\\.min\\..*$"

  # - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
  #   rev: v1.3.0
  #   hooks:
  #     - id: python-safety-dependencies-check
  #       name: safety
  #       always_run: true
  #       exclude: ".*"
  #       verbose: true
  #       args: ["requirements.txt", "--ignore=51457"]

  - repo: local
    hooks:
      - id: npm-audit
        name: npm-audit
        language: system
        entry: npm audit --audit-level=critical
        always_run: true
        exclude: ".*"
