default_language_version:
  python: python3.8

exclude: "^$"

fail_fast: false

repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.34.0
    hooks:
      - id: pyupgrade
        args: [--py38-plus]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-ast
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict

  - repo: https://github.com/rtts/djhtml
    rev: v1.5.1
    hooks:
      - id: djhtml
        args:
          - --tabwidth=2

  - repo: https://github.com/thibaudcolas/curlylint
    rev: v0.13.0
    hooks:
      - id: curlylint

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
      - id: black
        exclude: "^.*/migrations/.*.py$"
        args: [--line-length=79, --safe]

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==22.7.1
          - flake8-no-pep420==2.3.0
          - flake8-comprehensions==3.10.0

  - repo: local
    hooks:
      - id: safety
        name: safety
        entry: safety check
        language: system
        always_run: true
        exclude: ".*"

      - id: npm-audit
        name: npm-audit
        language: system
        entry: npm audit --audit-level=critical
        always_run: true
        exclude: ".*"
